load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")
load("@rules_python//python:py_library.bzl", "py_library")
load("@rules_python//python:py_test.bzl", "py_test")

exports_files(
    srcs = [
        "antlr.patch",
    ],
    visibility = ["//visibility:public"],
)
